install_velero:
  stage: extend
  tags:
    - infra
  script:
    - |
      # Setting up...
      . ./common/commonsetup.sh
      if [ "${DRYRUN}" == "yes" ] ; then echo "Dry run of ${CI_JOB_NAME} only. Nothing Done." ; exit 0 ; fi
    - |
      # Get TKC kubeconfig
      ${KUBECMD} -n ${KUBE_NAMESPACE} get secret ${TCL_NAME}-kubeconfig -o jsonpath='{.data.value}'  | base64 --decode > ./${TCL_NAME}.kubeconfig
      TKCKUBECMD="kubectl --kubeconfig=./${TCL_NAME}.kubeconfig --insecure-skip-tls-verify "
    - |
      # Install velero 
      echo Installing velero into ${TCL_NAME}
      MinIO_Svc_External_IP=${MinIO_Svc_External_IP:-192.168.2.8}
      echo Connecting to bucket velero at http://$MinIO_Svc_External_IP:9000
    - velero install --kubeconfig ./${TCL_NAME}.kubeconfig --provider aws --plugins velero/velero-plugin-for-aws:v1.1.0 --bucket velero --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://$MinIO_Svc_External_IP:9000 --use-volume-snapshots=false --secret-file $CREDS_VELERO
  when: manual
  only:
    refs:
      - master
    changes:
      - tkgclusters/tkg-cluster.yaml
