kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlabrunner-full-access
  namespace: gitlabrunner
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: gitlabrunner
  name: gitlab-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlabrunner-full-access
subjects:
- kind: ServiceAccount
  name: default
  namespace: gitlabrunner
